# Copyright (C) 2020, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

FROM container-registry.oracle.com/os/oraclelinux:7.9@sha256:5aa7df08f9ab8cd6237223b0b6c5fd605f140164235b462a01e8b9d56fb03daf as build_base

RUN yum update -y \
    && yum-config-manager --save --setopt=ol7_ociyum_config.skip_if_unavailable=true \
    && yum install -y oracle-golang-release-el7 \
    && yum-config-manager --enable ol7_developer_golang113 \
    && yum-config-manager --add-repo http://yum.oracle.com/repo/OracleLinux/OL7/developer/golang114/x86_64 \
    && yum install -y git gcc make golang-1.13.4-1.el7.x86_64 \
    && yum clean all \
    && go version

# Compile to /usr/bin
ENV GOBIN=/usr/bin

# Set go path
ENV GOPATH=/go

# Need to use specific WORKDIR to match alertmanager's source packages
WORKDIR /root/go/src/github.com/prometheus/pushgateway

COPY . .

ENV GO111MODULE=on
RUN make common-build common-test

FROM container-registry.oracle.com/os/oraclelinux:7-slim@sha256:fcc6f54bb01fc83319990bf5fa1b79f1dec93cbb87db3c5a8884a5a44148e7bb

COPY --from=build_base --chown=nobody:nobody /root/go/src/github.com/prometheus/pushgateway/pushgateway /bin/pushgateway

# Add license files to the image
COPY LICENSE NOTICE README.md THIRD_PARTY_LICENSES.txt /license/

# in OL7, user "nobody" has UID 99; specifying user by UID to faciltiate K8s
# confirming this is not running as root
USER       99
EXPOSE     9091
ENV        VERRAZZANO_PUSHGATEWAY_IGNORE_TYPES=true
ENV        VERRAZZANO_PUSHGATEWAY_200_COMPATIBILITY=true
ENTRYPOINT [ "/bin/pushgateway" ]
CMD [ "--log.level=warn", "--push.disable-consistency-check" ]
